# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    groups:
      dev-minor-patch:
        update-types:
          - minor
          - patch
        dependency-type: development
      prod-minor-patch:
        update-types:
          - minor
          - patch
        dependency-type: production

  - package-ecosystem: "docker"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"